version: '3'

services:
  frontend:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build: ./micro-api/
    ports:
      - '3001:3001'
